name: Deploy on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          cd /opt/prosbc-automation
          git config --global user.name "GitHub Runner"
          git config --global user.email "githubrunner@prosbcapp.com"
          git config --global --add safe.directory /opt/prosbc-automation
          git fetch origin
          git reset --hard origin/main
          sudo npm install --prefix backend_new
          sudo npm install --prefix frontend
          sudo npm run build --prefix frontend
          pm2 restart prosbc-backend || pm2 start backend_new/server.js --name prosbc-backend
          sudo nginx -s reload 