name: Deploy on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          cd /opt/prosbc-automation
          git config --global --add safe.directory /opt/prosbc-automation
          git pull origin main
          npm install --prefix backend_new
          npm install --prefix frontend
          npm run build --prefix frontend
          pm2 restart prosbc-backend || pm2 start backend_new/server.js --name prosbc-backend
          sudo nginx -s reload